# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: huawei-telemetry.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16huawei-telemetry.proto\x12\ttelemetry\"\xb7\x03\n\tTelemetry\x12\x13\n\x0bnode_id_str\x18\x01 \x01(\t\x12\x1b\n\x13subscription_id_str\x18\x02 \x01(\t\x12\x13\n\x0bsensor_path\x18\x03 \x01(\t\x12\x12\n\nproto_path\x18\r \x01(\t\x12\x15\n\rcollection_id\x18\x04 \x01(\x04\x12\x1d\n\x15\x63ollection_start_time\x18\x05 \x01(\x04\x12\x15\n\rmsg_timestamp\x18\x06 \x01(\x04\x12.\n\x08\x64\x61ta_gpb\x18\x07 \x01(\x0b\x32\x1c.telemetry.TelemetryGPBTable\x12\x1b\n\x13\x63ollection_end_time\x18\x08 \x01(\x04\x12\x16\n\x0e\x63urrent_period\x18\t \x01(\r\x12\x13\n\x0b\x65xcept_desc\x18\n \x01(\t\x12\x14\n\x0cproduct_name\x18\x0b \x01(\t\x12/\n\x08\x65ncoding\x18\x0c \x01(\x0e\x32\x1d.telemetry.Telemetry.Encoding\x12\x10\n\x08\x64\x61ta_str\x18\x0e \x01(\t\"/\n\x08\x45ncoding\x12\x10\n\x0c\x45ncoding_GPB\x10\x00\x12\x11\n\rEncoding_JSON\x10\x01\"<\n\x11TelemetryGPBTable\x12\'\n\x03row\x18\x01 \x03(\x0b\x32\x1a.telemetry.TelemetryRowGPB\"5\n\x0fTelemetryRowGPB\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x0f\n\x07\x63ontent\x18\x0b \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'huawei_telemetry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TELEMETRY']._serialized_start=38
  _globals['_TELEMETRY']._serialized_end=477
  _globals['_TELEMETRY_ENCODING']._serialized_start=430
  _globals['_TELEMETRY_ENCODING']._serialized_end=477
  _globals['_TELEMETRYGPBTABLE']._serialized_start=479
  _globals['_TELEMETRYGPBTABLE']._serialized_end=539
  _globals['_TELEMETRYROWGPB']._serialized_start=541
  _globals['_TELEMETRYROWGPB']._serialized_end=594
# @@protoc_insertion_point(module_scope)
