from(bucket: "study")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "F1NET")
  |> filter(fn: (r) => r["_field"] == "bad" or r["_field"] == "busy" or r["_field"] == "good")
  |> group(columns: ["_value"], mode: "by")