from(bucket: "study")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "dnac")
  |> filter(fn: (r) => r["_field"] == "cpu1")
  |> sort(columns: ["_value", "_time"], desc: false)
  |> limit(n: 5)