# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: arphello.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61rphello.proto\x12\x07get_arp\"#\n\narpRequest\x12\x15\n\rquery_content\x18\x01 \x01(\t\"\x1c\n\x08\x61rpReply\x12\x10\n\x08\x61rp_info\x18\x01 \x01(\t2A\n\x07get_arp\x12\x36\n\nLogin_info\x12\x13.get_arp.arpRequest\x1a\x11.get_arp.arpReply\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arphello_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARPREQUEST']._serialized_start=27
  _globals['_ARPREQUEST']._serialized_end=62
  _globals['_ARPREPLY']._serialized_start=64
  _globals['_ARPREPLY']._serialized_end=92
  _globals['_GET_ARP']._serialized_start=94
  _globals['_GET_ARP']._serialized_end=159
# @@protoc_insertion_point(module_scope)
